"""Registro de auditoria de acciones y eventos de seguridad

Revision ID: 59ba77e33f79
Revises: 659c9613f32d
Create Date: 2026-09-11 20:44:33.554049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ba77e33f79'
down_revision = '659c9613f32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('accion', sa.String(length=120), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_email', sa.String(length=255), nullable=True),
    sa.Column('rol', sa.String(length=30), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('metodo', sa.String(length=10), nullable=True),
    sa.Column('ruta', sa.String(length=300), nullable=True),
    sa.Column('resultado', sa.String(length=20), nullable=True),
    sa.Column('detalle', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_categoria'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
