"""Archiva los pedidos terminados en vez de borrarlos

Revision ID: 659c9613f32d
Revises: d83b77e11a68
Create Date: 2026-09-11 19:56:35.417155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659c9613f32d'
down_revision = 'd83b77e11a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
