"""Marca si el stock de un pedido cancelado ya fue devuelto al inventario

Revision ID: 85ce3126fe05
Revises: 365a03673312
Create Date: 2026-09-10 20:26:10.401653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ce3126fe05'
down_revision = '365a03673312'
branch_labels = None
depends_on = None


def upgrade():
    # server_default es necesario para que los pedidos ya existentes reciban un
    # valor al agregar la columna obligatoria.
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('stock_restored', sa.Boolean(), nullable=False, server_default=sa.false())
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('stock_restored')

    # ### end Alembic commands ###
