"""Guarda las referencias de entrega que escribe el cliente

Revision ID: d83b77e11a68
Revises: 6152b5a698bc
Create Date: 2026-09-11 19:16:22.449293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83b77e11a68'
down_revision = '6152b5a698bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_notes', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_notes')

    # ### end Alembic commands ###
